### ISSUE TITLE
The design of equation 11

### ISSUE THREAD

**Issue by Hugo-cell111** [qpc1611094/FPL#3]
Hi! Thank you for your solid and enlightening work! About the equation 11, although the motivation is strong, that is, to emphasize the importance of top-1 class prediction and weaken the contribution of other top-k classwise predictions, the equation is too complicated and a little bit counter-intuitive. Why not directly designing it as the probability margin divided by the sum of top-k probs? Why introducing log operation and amplitude factor A=50 into the weight equation? Thanks!

**Comment by qpc1611094** [comment]
The equation 11 is derived from Eq.10. Its simplest form is the probability margin divided by the sum of top-k probs as you mentioned, which can be seen as a linearly decreasing function. But in practice, we find a logarithmic decreasing function is better, and the radian A=50 is an empirical value
